set(NCTL_HEADERS
	${NCINE_ROOT}/include/nctl/algorithms.h
	${NCINE_ROOT}/include/nctl/iterator.h
	${NCINE_ROOT}/include/nctl/type_traits.h
	${NCINE_ROOT}/include/nctl/utility.h
	${NCINE_ROOT}/include/nctl/PointerMath.h
	${NCINE_ROOT}/include/nctl/Array.h
	${NCINE_ROOT}/include/nctl/ArrayIterator.h
	${NCINE_ROOT}/include/nctl/StaticArray.h
	${NCINE_ROOT}/include/nctl/List.h
	${NCINE_ROOT}/include/nctl/ListIterator.h
	${NCINE_ROOT}/include/nctl/CString.h
	${NCINE_ROOT}/include/nctl/Utf8.h
	${NCINE_ROOT}/include/nctl/String.h
	${NCINE_ROOT}/include/nctl/StaticString.h
	${NCINE_ROOT}/include/nctl/StringIterator.h
	${NCINE_ROOT}/include/nctl/StringView.h
	${NCINE_ROOT}/include/nctl/HashFunctions.h
	${NCINE_ROOT}/include/nctl/HashMap.h
	${NCINE_ROOT}/include/nctl/HashMapIterator.h
	${NCINE_ROOT}/include/nctl/StaticHashMap.h
	${NCINE_ROOT}/include/nctl/StaticHashMapIterator.h
	${NCINE_ROOT}/include/nctl/HashMapList.h
	${NCINE_ROOT}/include/nctl/HashMapListIterator.h
	${NCINE_ROOT}/include/nctl/HashSet.h
	${NCINE_ROOT}/include/nctl/HashSetIterator.h
	${NCINE_ROOT}/include/nctl/StaticHashSet.h
	${NCINE_ROOT}/include/nctl/StaticHashSetIterator.h
	${NCINE_ROOT}/include/nctl/HashSetList.h
	${NCINE_ROOT}/include/nctl/HashSetListIterator.h
	${NCINE_ROOT}/include/nctl/SparseSet.h
	${NCINE_ROOT}/include/nctl/SparseSetIterator.h
	${NCINE_ROOT}/include/nctl/ReverseIterator.h
	${NCINE_ROOT}/include/nctl/Atomic.h
	${NCINE_ROOT}/include/nctl/UniquePtr.h
	${NCINE_ROOT}/include/nctl/SharedPtr.h
	${NCINE_ROOT}/include/nctl/BitSet.h
	${NCINE_ROOT}/include/nctl/Optional.h
	${NCINE_ROOT}/include/nctl/Pair.h
	${NCINE_ROOT}/include/nctl/Span.h
)
