if(APPLE)
	function(split_extra_frameworks PREFIX LIBRARIES)
		foreach(LIBRARY ${LIBRARIES})
			string(REGEX MATCH "^-framework " FOUND ${LIBRARY})
			if(NOT FOUND STREQUAL "")
				list(APPEND FRAMEWORK_LINKS ${LIBRARY})
			else()
				list(APPEND FRAMEWORK_DIR ${LIBRARY})
			endif()
		endforeach()
		set(${PREFIX}_FRAMEWORK_LINKS ${FRAMEWORK_LINKS} PARENT_SCOPE)
		set(${PREFIX}_FRAMEWORK_DIR ${FRAMEWORK_DIR} PARENT_SCOPE)
	endfunction()

	# --------------------------------
	if(GLEW_FOUND)
		get_target_property(GLEW_LIBRARY_RELEASE GLEW::GLEW IMPORTED_LOCATION_RELEASE)
		set_target_properties(GLEW::GLEW PROPERTIES
			IMPORTED_LOCATION ${GLEW_LIBRARY_RELEASE}/glew
			IMPORTED_LOCATION_RELEASE ${GLEW_LIBRARY_RELEASE}/glew
			IMPORTED_LOCATION_DEBUG ${GLEW_LIBRARY_RELEASE}/glew)
	endif()

	if(GLFW_FOUND)
		add_library(GLFW::GLFW SHARED IMPORTED)
		split_extra_frameworks(GLFW "${GLFW_LIBRARY}")
		set_target_properties(GLFW::GLFW PROPERTIES
			IMPORTED_LOCATION ${GLFW_FRAMEWORK_DIR}/glfw
			INTERFACE_LINK_LIBRARIES ${GLFW_FRAMEWORK_LINKS}
			INTERFACE_COMPILE_DEFINITIONS "GLFW_NO_GLU"
			INTERFACE_INCLUDE_DIRECTORIES ${GLFW_INCLUDE_DIR})
	endif()

	if(SDL2_FOUND)
		add_library(SDL2::SDL2 SHARED IMPORTED)
		split_extra_frameworks(SDL2 "${SDL2_LIBRARY}")
		set_target_properties(SDL2::SDL2 PROPERTIES
			IMPORTED_LOCATION ${SDL2_FRAMEWORK_DIR}/sdl2
			INTERFACE_LINK_LIBRARIES ${SDL2_FRAMEWORK_LINKS}
			INTERFACE_INCLUDE_DIRECTORIES ${SDL2_INCLUDE_DIR})
	endif()

	if(PNG_FOUND)
		get_target_property(ZLIB_LIBRARY_RELEASE ZLIB::ZLIB IMPORTED_LOCATION_RELEASE)
		set_target_properties(ZLIB::ZLIB PROPERTIES
			IMPORTED_LOCATION ${ZLIB_LIBRARY_RELEASE}/zlib
			IMPORTED_LOCATION_RELEASE ${ZLIB_LIBRARY_RELEASE}/zlib
			IMPORTED_LOCATION_DEBUG ${ZLIB_LIBRARY_RELEASE}/zlib)
		get_target_property(PNG_LIBRARY_RELEASE PNG::PNG IMPORTED_LOCATION_RELEASE)
		set_target_properties(PNG::PNG PROPERTIES
			IMPORTED_LOCATION ${PNG_LIBRARY_RELEASE}/png
			IMPORTED_LOCATION_RELEASE ${PNG_LIBRARY_RELEASE}/png
			IMPORTED_LOCATION_DEBUG ${PNG_LIBRARY_RELEASE}/png)
	endif()

	if(WEBP_FOUND)
		add_library(WebP::WebP SHARED IMPORTED)
		set_target_properties(WebP::WebP PROPERTIES
			IMPORTED_LOCATION ${WEBP_LIBRARY}/webp
			INTERFACE_INCLUDE_DIRECTORIES ${WEBP_INCLUDE_DIR})
	endif()

	if(OPENAL_FOUND)
		add_library(OpenAL::AL SHARED IMPORTED)
		set_target_properties(OpenAL::AL PROPERTIES
			IMPORTED_LOCATION ${OPENAL_LIBRARY}/openal
			INTERFACE_INCLUDE_DIRECTORIES ${OPENAL_INCLUDE_DIR})

		if(VORBIS_FOUND)
			add_library(Vorbis::Vorbisfile SHARED IMPORTED)
			set_target_properties(Vorbis::Vorbisfile PROPERTIES
				IMPORTED_LOCATION ${VORBISFILE_LIBRARY}/vorbisfile
				INTERFACE_INCLUDE_DIRECTORIES ${VORBIS_INCLUDE_DIR})
		endif()
	endif()

	if(LUA_FOUND)
		add_library(Lua::Lua SHARED IMPORTED)
		set_target_properties(Lua::Lua PROPERTIES
			IMPORTED_LOCATION ${LUA_LIBRARY}/lua
			INTERFACE_INCLUDE_DIRECTORIES ${LUA_INCLUDE_DIR})
	endif()
endif()
