if(EMSCRIPTEN)
	return()
endif()

if(NOT NCINE_DYNAMIC_LIBRARY OR (NOT CMAKE_SKIP_RPATH AND NOT CMAKE_SKIP_INSTALL_RPATH))
	find_package(Threads)
	if (NOT ANDROID)
		find_package(OpenGL REQUIRED)
	endif()
	if(NOT MSVC AND NOT ANDROID) # GCC and LLVM
		if(APPLE)
			set(CMAKE_FRAMEWORK_PATH ${FRAMEWORKS_DIR})
			set(CMAKE_MACOSX_RPATH ON)
		endif()

		if(WIN32)
			find_package(GLEW REQUIRED)
		else()
			find_package(GLEW)
		endif()
		if(NCPROJECT_ARM_PROCESSOR)
			include(check_atomic)
			find_package(OpenGLES2)
		endif()
		find_package(GLFW)
		find_package(SDL2)
		find_package(PNG)
		find_package(OpenAL)
		find_package(WebP)
		find_package(Vorbis)

		# Older CMake versions do not support Lua 5.4 or newer if not required explicitly
		find_package(Lua 5.5)
		if(NOT LUA_FOUND)
			find_package(Lua)
		endif()
	endif()
endif()
