if(EMSCRIPTEN)
	return()
elseif(APPLE)
	set(CMAKE_FRAMEWORK_PATH "${PARENT_SOURCE_DIR}/nCine-external")
	set(CMAKE_MACOSX_RPATH ON)

	if(NOT IS_DIRECTORY ${CMAKE_FRAMEWORK_PATH})
		message(FATAL_ERROR "nCine external OS X frameworks directory not found at: ${CMAKE_FRAMEWORK_PATH}")
	else()
		message(STATUS "nCine external OS X frameworks directory: ${CMAKE_FRAMEWORK_PATH}")
	endif()
endif()

if(NCINE_WITH_CRASHPAD)
	find_package(Crashpad)
endif()
if(NCINE_WITH_THREADS)
	find_package(Threads)
endif()
if(NOT ANDROID)
	find_package(OpenGL REQUIRED)
endif()
if(NOT MSVC AND NOT ANDROID)
	if(WIN32)
		find_package(GLEW REQUIRED)
	else()
		if(NCINE_WITH_GLEW)
			find_package(GLEW)
		endif()
	endif()
	if(NCINE_ARM_PROCESSOR)
		include(check_atomic)
		find_package(OpenGLES2)
	endif()
	# Look for both GLFW and SDL2 to make the fallback logic work
	find_package(GLFW)
	find_package(SDL2)
	if(NCINE_WITH_PNG)
		find_package(PNG)
	endif()
	if(NCINE_WITH_WEBP)
		find_package(WebP)
	endif()
	if(NCINE_WITH_AUDIO)
		find_package(OpenAL)
		if(NCINE_WITH_VORBIS)
			find_package(Vorbis)
		endif()
	endif()
	if(NCINE_WITH_LUA)
		# Older CMake versions do not support Lua 5.4 or newer if not required explicitly
		find_package(Lua 5.5)
		if(NOT LUA_FOUND)
			find_package(Lua)
		endif()
	endif()
endif()

if(NOT ANDROID AND NCINE_PREFERRED_BACKEND STREQUAL "QT5")
	find_package(Qt5 COMPONENTS Widgets REQUIRED)
	find_package(Qt5Gamepad)
endif()
