set(SOURCES
	${NCINE_ROOT}/src/base/Object.cpp
	${NCINE_ROOT}/src/base/String.cpp
	${NCINE_ROOT}/src/ServiceLocator.cpp
	${NCINE_ROOT}/src/FileLogger.cpp
	${NCINE_ROOT}/src/ArrayIndexer.cpp
	${NCINE_ROOT}/src/Timer.cpp
	${NCINE_ROOT}/src/FrameTimer.cpp
	${NCINE_ROOT}/src/ProfileVariable.cpp
	${NCINE_ROOT}/src/Font.cpp
	${NCINE_ROOT}/src/FontGlyph.cpp
	${NCINE_ROOT}/src/IFile.cpp
	${NCINE_ROOT}/src/StandardFile.cpp
	${NCINE_ROOT}/src/IInputManager.cpp
	${NCINE_ROOT}/src/JoyMapping.cpp
	${NCINE_ROOT}/src/graphics/IGfxDevice.cpp
	${NCINE_ROOT}/src/graphics/GfxCapabilities.cpp
	${NCINE_ROOT}/src/graphics/RenderResources.cpp
	${NCINE_ROOT}/src/graphics/RenderCommand.cpp
	${NCINE_ROOT}/src/graphics/RenderQueue.cpp
	${NCINE_ROOT}/src/graphics/Material.cpp
	${NCINE_ROOT}/src/graphics/Geometry.cpp
	${NCINE_ROOT}/src/graphics/TextureFormat.cpp
	${NCINE_ROOT}/src/graphics/ITextureLoader.cpp
	${NCINE_ROOT}/src/graphics/TextureLoaderDds.cpp
	${NCINE_ROOT}/src/graphics/TextureLoaderPvr.cpp
	${NCINE_ROOT}/src/graphics/TextureLoaderKtx.cpp
	${NCINE_ROOT}/src/graphics/Texture.cpp
	${NCINE_ROOT}/src/graphics/ProfilePlotter.cpp
	${NCINE_ROOT}/src/graphics/PlottingVariable.cpp
	${NCINE_ROOT}/src/graphics/LinePlotter.cpp
	${NCINE_ROOT}/src/graphics/StackedBarPlotter.cpp
	${NCINE_ROOT}/src/graphics/DrawableNode.cpp
	${NCINE_ROOT}/src/graphics/SceneNode.cpp
	${NCINE_ROOT}/src/graphics/Sprite.cpp
	${NCINE_ROOT}/src/Application.cpp
	${NCINE_ROOT}/src/AppConfiguration.cpp
	${NCINE_ROOT}/src/graphics/Particle.cpp
	${NCINE_ROOT}/src/graphics/ParticleAffectors.cpp
	${NCINE_ROOT}/src/graphics/ParticleSystem.cpp
	${NCINE_ROOT}/src/graphics/TextNode.cpp
	${NCINE_ROOT}/src/graphics/RectAnimation.cpp
	${NCINE_ROOT}/src/graphics/AnimatedSprite.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLBufferObject.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLFramebufferObject.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLRenderbuffer.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLShader.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLShaderProgram.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLShaderUniforms.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLUniform.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLUniformCache.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLShaderAttributes.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLAttribute.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLVertexAttribute.cpp
	${NCINE_ROOT}/src/graphics/opengl/GLTexture.cpp
)
