set(PRIVATE_HEADERS
	src/include/common_headers.h
	src/include/ArrayIndexer.h
	src/include/FrameTimer.h
	src/include/StandardFile.h
	src/include/FileLogger.h
	src/include/FontGlyph.h
	src/include/ProfileVariable.h
	src/include/PlottingVariable.h
	src/include/ProfilePlotter.h
	src/include/LinePlotter.h
	src/include/StackedBarPlotter.h
	src/include/GfxCapabilities.h
	src/include/RenderResources.h
	src/include/RenderCommand.h
	src/include/RenderQueue.h
	src/include/Material.h
	src/include/Geometry.h
	src/include/Particle.h
	src/include/TextureFormat.h
	src/include/ITextureLoader.h
	src/include/TextureLoaderDds.h
	src/include/TextureLoaderPvr.h
	src/include/TextureLoaderKtx.h
	src/include/GLHashMap.h
	src/include/GLBufferObject.h
	src/include/GLBufferObject.h
	src/include/GLFramebufferObject.h
	src/include/GLRenderbuffer.h
	src/include/GLShader.h
	src/include/GLShaderProgram.h
	src/include/GLShaderUniforms.h
	src/include/GLUniform.h
	src/include/GLUniformCache.h
	src/include/GLShaderAttributes.h
	src/include/GLAttribute.h
	src/include/GLVertexAttribute.h
	src/include/GLTexture.h
)