set(PRIVATE_HEADERS
	${NCINE_ROOT}/src/include/common_headers.h
	${NCINE_ROOT}/src/include/return_macros.h
	${NCINE_ROOT}/src/include/Clock.h
	${NCINE_ROOT}/src/include/ArrayIndexer.h
	${NCINE_ROOT}/src/include/FrameTimer.h
	${NCINE_ROOT}/src/include/MemoryFile.h
	${NCINE_ROOT}/src/include/StandardFile.h
	${NCINE_ROOT}/src/include/FileLogger.h
	${NCINE_ROOT}/src/include/JoyMapping.h
	${NCINE_ROOT}/src/input/JoyMappingDb.h
	${NCINE_ROOT}/src/include/FntParser.h
	${NCINE_ROOT}/src/include/FontGlyph.h
	${NCINE_ROOT}/src/include/GfxCapabilities.h
	${NCINE_ROOT}/src/include/RenderResources.h
	${NCINE_ROOT}/src/include/RenderCommand.h
	${NCINE_ROOT}/src/include/RenderQueue.h
	${NCINE_ROOT}/src/include/Material.h
	${NCINE_ROOT}/src/include/Geometry.h
	${NCINE_ROOT}/src/include/Particle.h
	${NCINE_ROOT}/src/include/TextureFormat.h
	${NCINE_ROOT}/src/include/ITextureLoader.h
	${NCINE_ROOT}/src/include/TextureLoaderRaw.h
	${NCINE_ROOT}/src/include/TextureLoaderDds.h
	${NCINE_ROOT}/src/include/TextureLoaderPvr.h
	${NCINE_ROOT}/src/include/TextureLoaderKtx.h
	${NCINE_ROOT}/src/include/ITextureSaver.h
	${NCINE_ROOT}/src/include/GLHashMap.h
	${NCINE_ROOT}/src/include/GLBufferObject.h
	${NCINE_ROOT}/src/include/GLBufferObject.h
	${NCINE_ROOT}/src/include/GLFramebufferObject.h
	${NCINE_ROOT}/src/include/GLRenderbuffer.h
	${NCINE_ROOT}/src/include/GLShader.h
	${NCINE_ROOT}/src/include/GLShaderProgram.h
	${NCINE_ROOT}/src/include/GLShaderUniforms.h
	${NCINE_ROOT}/src/include/GLUniform.h
	${NCINE_ROOT}/src/include/GLUniformCache.h
	${NCINE_ROOT}/src/include/GLShaderAttributes.h
	${NCINE_ROOT}/src/include/GLAttribute.h
	${NCINE_ROOT}/src/include/GLTexture.h
	${NCINE_ROOT}/src/include/GLVertexArrayObject.h
	${NCINE_ROOT}/src/include/GLUniformBlock.h
	${NCINE_ROOT}/src/include/GLUniformBlockCache.h
	${NCINE_ROOT}/src/include/GLShaderUniformBlocks.h
	${NCINE_ROOT}/src/include/GLScissorTest.h
	${NCINE_ROOT}/src/include/GLDepthTest.h
	${NCINE_ROOT}/src/include/GLBlending.h
	${NCINE_ROOT}/src/include/GLCullFace.h
	${NCINE_ROOT}/src/include/RenderBuffersManager.h
	${NCINE_ROOT}/src/include/RenderBatcher.h
	${NCINE_ROOT}/src/include/GLDebug.h
	${NCINE_ROOT}/src/include/RenderStatistics.h
	${NCINE_ROOT}/src/include/GLVertexFormat.h
	${NCINE_ROOT}/src/include/RenderVaoPool.h
)
