set(HEADERS
	${NCINE_ROOT}/include/common_defines.h
	${NCINE_ROOT}/include/common_constants.h
	${NCINE_ROOT}/include/common_macros.h
	${NCINE_ROOT}/include/nctl/algorithms.h
	${NCINE_ROOT}/include/nctl/iterator.h
	${NCINE_ROOT}/include/nctl/type_traits.h
	${NCINE_ROOT}/include/nctl/utility.h
	${NCINE_ROOT}/include/nctl/Array.h
	${NCINE_ROOT}/include/nctl/ArrayIterator.h
	${NCINE_ROOT}/include/nctl/StaticArray.h
	${NCINE_ROOT}/include/nctl/List.h
	${NCINE_ROOT}/include/nctl/ListIterator.h
	${NCINE_ROOT}/include/nctl/String.h
	${NCINE_ROOT}/include/nctl/StringIterator.h
	${NCINE_ROOT}/include/nctl/HashMap.h
	${NCINE_ROOT}/include/nctl/HashFunctions.h
	${NCINE_ROOT}/include/nctl/HashMapIterator.h
	${NCINE_ROOT}/include/nctl/ReverseIterator.h
	${NCINE_ROOT}/include/nctl/Atomic.h
	${NCINE_ROOT}/include/nctl/UniquePtr.h
	${NCINE_ROOT}/include/nctl/SharedPtr.h
	${NCINE_ROOT}/include/Rect.h
	${NCINE_ROOT}/include/Color.h
	${NCINE_ROOT}/include/Object.h
	${NCINE_ROOT}/include/DrawableNode.h
	${NCINE_ROOT}/include/IAppEventHandler.h
	${NCINE_ROOT}/include/IInputEventHandler.h
	${NCINE_ROOT}/include/InputEvents.h
	${NCINE_ROOT}/include/IInputManager.h
	${NCINE_ROOT}/include/Keys.h
	${NCINE_ROOT}/include/Vector2.h
	${NCINE_ROOT}/include/Vector3.h
	${NCINE_ROOT}/include/Vector4.h
	${NCINE_ROOT}/include/Matrix4x4.h
	${NCINE_ROOT}/include/Quaternion.h
	${NCINE_ROOT}/include/ServiceLocator.h
	${NCINE_ROOT}/include/DisplayMode.h
	${NCINE_ROOT}/include/Timer.h
	${NCINE_ROOT}/include/Font.h
	${NCINE_ROOT}/include/IFile.h
	${NCINE_ROOT}/include/IGfxDevice.h
	${NCINE_ROOT}/include/IGfxCapabilities.h
	${NCINE_ROOT}/include/Texture.h
	${NCINE_ROOT}/include/SceneNode.h
	${NCINE_ROOT}/include/BaseSprite.h
	${NCINE_ROOT}/include/Sprite.h
	${NCINE_ROOT}/include/MeshSprite.h
	${NCINE_ROOT}/include/Application.h
	${NCINE_ROOT}/include/AppConfiguration.h
	${NCINE_ROOT}/include/ParticleAffectors.h
	${NCINE_ROOT}/include/ParticleSystem.h
	${NCINE_ROOT}/include/TextNode.h
	${NCINE_ROOT}/include/RectAnimation.h
	${NCINE_ROOT}/include/AnimatedSprite.h
)
